version: '3'

services:
  photo-importer:
    container_name: photo-importer  # Forces consistent naming
    build: .  # Build the Dockerfile in the current directory
    restart: unless-stopped
    environment:
      - NTFY_TOPIC=${NTFY_TOPIC}
      - NTFY_SERVER=${NTFY_SERVER}
      - SD_CARD_MOUNT=/test_media
      - DESTINATION_BASE=/test_output
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./logs:/app/logs
      - ./test_media:/test_media  # Local test directory
      - ./test_output:/test_output  # Local output directory
