name: Publish Docker Image

on:
  push:
    branches: ['main']
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'requirements.txt'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/skitchbeatz/photo-importer:latest
          platforms: linux/arm64
          provenance: false
